`timescale 1ns/1ps
// Frequency-domain receive integration for the variable-length v2 PHY.
//
// The time-domain synchronizer/replay and the XFFT are intentionally kept at
// the boundary of this block.  The input is the natural-order XFFT stream
// plus a symbol kind generated by the replay/FFT wrapper:
//   0: LTF1, 1: LTF2, 2: PHY Header, 3: payload data, 4: Midamble.
//
// LTF1/LTF2 -> dual-LTF channel estimator -> H memory
// Header/data -> pilot tracking, equalization, LLR packetizer
// Header LLR -> low-resource TDM Viterbi/CRC/field checker
// Payload LLR is released only after a valid Header.  The block therefore
// has a bounded storage requirement and is safe to put after a throttled
// XFFT stream while the 56 us Header decoder is running.
module cofdm_phy_rx_v2_freq_top #(
    parameter integer LLR_W = 16,
    parameter integer NFFT = 256,
    parameter [NFFT-1:0] ACTIVE_MASK = (NFFT == 256) ?
      {{{100{1'b1}}},{{55{1'b0}}},{{100{1'b1}}},1'b0} : {NFFT{1'b1}},
    parameter integer MAX_PAYLOAD = 2048
) (
    input  wire                         clk,
    input  wire                         rst,
    input  wire                         frame_start,
    input wire [23:0] inv_noise_q16,
    output wire symbol_done, payload_cw_first, payload_cw_last,
    output wire [15:0] n_codewords,
    input  wire                         fft_valid,
    output wire                         fft_ready,
    input  wire                         fft_last,
    input  wire [7:0]                   fft_bin,
    input  wire [2:0]                   fft_symbol_kind,
    input  wire signed [15:0]            fft_re,
    input  wire signed [15:0]            fft_im,
    output wire                         payload_valid,
    output wire                         payload_last,
    output wire signed [LLR_W-1:0]       payload_llr,
    input  wire                         payload_ready,
    output wire                         header_valid,
    output wire                         header_ok,
    output wire                         crc_ok,
    output wire [11:0]                  payload_bytes,
    output wire [6:0]                   scrambler_seed,
    output wire [1:0]                   midamble_code,
    output wire                         header_error,
    output wire                         header_busy,
    output wire                         channel_done,
    output wire                         channel_error,
    output wire [47:0]                  noise_variance,
    output wire                         noise_valid,
    output wire                         frame_error
);
    localparam [2:0] KIND_LTF1=3'd0, KIND_LTF2=3'd1,
                     KIND_HEADER=3'd2, KIND_DATA=3'd3,
                     KIND_MIDAMBLE=3'd4;

    wire is_ltf = (fft_symbol_kind == KIND_LTF1) ||
                  (fft_symbol_kind == KIND_LTF2);
    wire is_header = (fft_symbol_kind == KIND_HEADER);
    wire is_data = (fft_symbol_kind == KIND_DATA);
    wire is_midamble = (fft_symbol_kind == KIND_MIDAMBLE);
    wire is_payload_symbol = is_header || is_data;

    // The LTF chain consumes one bin per cycle and has no backpressure in its
    // current implementation.  Payload backpressure is propagated from the
    // Header gate through pre_ldpc_stream to the XFFT input.
    wire ltf_ready;
    wire ltf_valid = fft_valid && is_ltf;
    wire ltf_last = fft_last && is_ltf;
    wire signed [17:0] h_re, h_im;
    wire [7:0] h_bin;
    wire h_valid;
    wire h_last;
    wire channel_ready_unused;
    wire channel_error_int;
    wire [31:0] noise_count_unused;
    cofdm_ltf_channel_chain #(.NFFT(NFFT),.ACTIVE_MASK(ACTIVE_MASK)) u_channel (
      .clk,.rst(frame_start|rst),
      .fft_out_valid(ltf_valid),.fft_out_ready(ltf_ready),
      .fft_out_last(ltf_last),.fft_out_re(fft_re),.fft_out_im(fft_im),
      .channel_valid(h_valid),.channel_last(h_last),.channel_bin(h_bin),
      .channel_re(h_re),.channel_im(h_im),.channel_done,
      .channel_ready(channel_ready_unused),.channel_error(channel_error_int),
      .noise_variance,.noise_valid,.noise_sample_count(noise_count_unused),
      .h_rd_en(1'b0),.h_rd_bin(8'd0),.h_rd_re(),.h_rd_im(),.h_valid());

    reg [15:0] n_codewords_reg;
    reg [16:0] cw_remaining;
    reg [15:0] cw_count_work;
    reg cw_calc_busy;
    wire config_ready = (n_codewords_reg != 0) && !cw_calc_busy;
    assign n_codewords = n_codewords_reg;

    reg header_accepted;
    always @(posedge clk) begin
      if(rst || frame_start) header_accepted<=0;
      else if(header_ok && config_ready) header_accepted<=1'b1;
    end
    wire allow_symbol=is_header || (is_data && header_accepted);
    wire pre_fft_valid = fft_valid && allow_symbol;
    wire pre_fft_ready;
    wire pre_symbol_header = is_header;
    wire pre_pilot_skip = fft_valid && fft_last && is_midamble;

    always @(posedge clk) begin
      if (rst || frame_start) begin
        n_codewords_reg<=0; cw_remaining<=0; cw_count_work<=0; cw_calc_busy<=0;
      end else begin
        if (header_valid && header_ok && !cw_calc_busy) begin
          cw_remaining <= payload_bytes * 17'd8 + 17'd32;
          cw_count_work <= 0;
          cw_calc_busy <= 1'b1;
          n_codewords_reg <= 0;
        end else if (cw_calc_busy) begin
          if (cw_remaining > 17'd324) begin
            cw_remaining <= cw_remaining - 17'd324;
            cw_count_work <= cw_count_work + 1'b1;
          end else begin
            n_codewords_reg <= cw_count_work + 1'b1;
            cw_calc_busy <= 1'b0;
          end
        end
      end
    end

    wire pre_out_valid, pre_out_ready, pre_out_header, pre_out_last;
    wire signed [LLR_W-1:0] pre_out_llr;
    wire pre_cw_first, pre_cw_last;
    wire pre_frame_error;
    cofdm_pre_ldpc_stream #(.LLR_W(LLR_W)) u_pre (
      .clk,.rst,.frame_start,
      .h_load_valid(h_valid),.h_load_last(h_last),.h_load_bin(h_bin),
      .h_load_re(h_re),.h_load_im(h_im),.h_load_ready(),
      .fft_valid(pre_fft_valid),.fft_last(fft_last),.fft_bin,
      .fft_re,.fft_im,.fft_ready(pre_fft_ready),
      .symbol_header(pre_symbol_header),.pilot_skip_midamble(pre_pilot_skip),
      .inv_noise_q16,.n_codewords,
      .out_valid(pre_out_valid),.out_ready(pre_out_ready),.out_llr(pre_out_llr),
      .out_header(pre_out_header),.out_symbol_last(pre_out_last),
      .out_cw_first(pre_cw_first),.out_cw_last(pre_cw_last),
      .symbol_done(symbol_done),.frame_error(pre_frame_error));

    cofdm_v2_rx_header_path #(.LLR_W(LLR_W),.GATE_CONFIG(1)) u_header (
      .clk,.rst,.frame_start,
      .stream_valid(pre_out_valid),.stream_header(pre_out_header),
      .stream_last(pre_out_last),.stream_llr(pre_out_llr),
      .stream_cw_first(pre_cw_first),.stream_cw_last(pre_cw_last),
      .config_ready,
      .stream_ready(pre_out_ready),.payload_valid,.payload_last,
      .payload_cw_first,.payload_cw_last,.payload_llr,.payload_ready,.header_valid,.header_ok,.crc_ok,
      .payload_bytes,.scrambler_seed,.midamble_code,.header_error,
      .busy(header_busy));

    // LTF and Midamble samples are consumed even though no LLR is emitted.
    // For a normal AXI stream the two routes are mutually exclusive.
    assign fft_ready = is_ltf ? ltf_ready :
                       is_payload_symbol ? (pre_fft_ready && allow_symbol) : 1'b1;
    assign channel_error=channel_error_int;
    assign frame_error = channel_error_int | pre_frame_error;

endmodule
