function export_ltf_channel_vectors(outDir)
%EXPORT_LTF_CHANNEL_VECTORS Fixed-point golden vectors for RTL LTF checking.
% The expected values intentionally model the RTL integer operations rather
% than reusing floating-point H. This catches ROM sign/order, arithmetic shift,
% saturation, bin numbering, and the variance normalization independently.
root=fileparts(mfilename('fullpath')); addpath(root);
if nargin<1, outDir=fullfile(root,'vectors','ltf_channel'); end
if ~exist(outDir,'dir'), mkdir(outDir); end
c=cofdm.config(); cofdm.seed_rng(20260929);
active=c.activeBins-1; nfft=c.nfft; F=14; coefF=15;
t=cofdm.training(c);
t1=zeros(nfft,1); t2=zeros(nfft,1);
t1(c.activeBins)=qcomp(t.ltf(:,1),coefF,16);
t2(c.activeBins)=qcomp(t.ltf(:,2),coefF,16);
% A deterministic frequency-selective channel plus repeatable LTF noise.
H=0.72*exp(-1j*2*pi*c.active*[2 11 27]/c.nfft)*[1;0.23*exp(0.4j);0.08*exp(-0.7j)];
n1=0.004*(randn(numel(c.active),1)+1j*randn(numel(c.active),1));
n2=0.004*(randn(numel(c.active),1)+1j*randn(numel(c.active),1));
y1=zeros(nfft,1); y2=zeros(nfft,1);
y1(c.activeBins)=qcomp(H.*t.ltf(:,1)+n1,15,16);
y2(c.activeBins)=qcomp(H.*t.ltf(:,2)+n2,15,16);

% Exact RTL model: (Y*conj(T)) >>> (2*(15)-14), then average.
h1=zeros(nfft,1); h2=zeros(nfft,1); havg=zeros(nfft,1);
for k=active(:).'
    h1(k+1)=cmul_shift(y1(k+1),t1(k+1),16,F,18);
    h2(k+1)=cmul_shift(y2(k+1),t2(k+1),16,F,18);
    havg(k+1)=complex(sat(floor((real(h1(k+1))+real(h2(k+1)))/2),18), ...
                     sat(floor((imag(h1(k+1))+imag(h2(k+1)))/2),18));
end
sumPow=uint64(0);
for k=active(:).'
    d=h2(k+1)-h1(k+1); sumPow=sumPow+uint64(real(d)*real(d)+imag(d)*imag(d));
end
nvRecip=floor((2^24+numel(active))/(2*numel(active)));
noiseVar=floor(double(sumPow)*nvRecip/2^24);
write_hex(fullfile(outDir,'ltf1_re.hex'),real_int(y1),16);
write_hex(fullfile(outDir,'ltf1_im.hex'),imag_int(y1),16);
write_hex(fullfile(outDir,'ltf2_re.hex'),real_int(y2),16);
write_hex(fullfile(outDir,'ltf2_im.hex'),imag_int(y2),16);
write_hex(fullfile(outDir,'expected_h_re.hex'),real_int(havg),18);
write_hex(fullfile(outDir,'expected_h_im.hex'),imag_int(havg),18);
write_hex(fullfile(outDir,'expected_noise.hex'),noiseVar,48);
fid=fopen(fullfile(outDir,'expected.txt'),'w'); assert(fid>=0); cl=onCleanup(@()fclose(fid));
fprintf(fid,'H_FRAC_BITS=14 ACTIVE_COUNT=%d NOISE_VARIANCE_Q28=%d\n',numel(active),noiseVar);
fprintf(fid,'Generated by export_ltf_channel_vectors seed=20260929\n');
fprintf(fid,'Input files are 256 natural FFT bins, signed two-complement hex.\n');
fprintf(fid,'Expected H files are signed Q18.14; variance is Q0.28.\n');
fprintf('Exported LTF channel RTL vectors to %s\n',outDir);
end

function z=qcomp(x,f,b)
lo=-2^(b-1); hi=2^(b-1)-1; z=complex(max(lo,min(hi,round(real(x)*2^f))),max(lo,min(hi,round(imag(x)*2^f))));
end
function z=cmul_shift(a,b,sh,f,bits)
rr=real(a)*real(b)+imag(a)*imag(b); ii=imag(a)*real(b)-real(a)*imag(b);
z=complex(sat(floor(rr/2^sh),bits),sat(floor(ii/2^sh),bits));
end
function y=sat(x,b)
y=max(-2^(b-1),min(2^(b-1)-1,x));
end
function y=real_int(x), y=round(real(x)); end
function y=imag_int(x), y=round(imag(x)); end
function write_hex(path,x,b)
fid=fopen(path,'w'); assert(fid>=0); cl=onCleanup(@()fclose(fid)); modv=2^b;
for k=1:numel(x), v=mod(x(k),modv); fprintf(fid,'%0*X\n',ceil(b/4),v); end
end
