function rows = run_compact_comparison(snrDb,nFrames,outPath,seed,quantized)
% Same-IQ comparison against the previous high-complexity proposed receiver.
if nargin<1, snrDb=[4 6 8]; end
if nargin<2, nFrames=20; end
if nargin<3, outPath=''; end
if nargin<4, seed=20260926; end
if nargin<5, quantized=false; end
options=struct('seed',seed,'quantizedDecoder',quantized);
options.modes={'proposed','safe_window','compact_channel','compact'};
options.channels={struct('name','flat','delays',0,'gains',1), ...
    struct('name','short_multipath','delays',[0 3 9], ...
        'gains',[1 0.25*exp(0.6j) 0.12*exp(-1j)]), ...
    struct('name','late_strong','delays',[0 10 23], ...
        'gains',[0.25 1 0.3*exp(0.7j)]), ...
    struct('name','cp_edge','delays',[0 31],'gains',[0.65 1], ...
        'cfoHz',-220e3,'offset',83), ...
    struct('name','dense','delays',[0 2 5 9 14 18 23 28], ...
        'gains',[0.5 0.2j -0.35 0.25 1 0.3j -0.2 0.25], ...
        'cfoHz',65e3,'offset',11)};
rows=run_receiver_comparison(snrDb,nFrames,outPath,options);
end
