function rows = run_fixed_comparison(snrDb,nFrames,outPath,seed,quantized,randomPhases)
% Same IQ for old compact / centered window / centered with fixed FIR + ROM.
if nargin<1, snrDb=[4 6]; end
if nargin<2, nFrames=20; end
if nargin<3, outPath=''; end
if nargin<4, seed=20261001; end
if nargin<5, quantized=false; end
if nargin<6, randomPhases=false; end
options=struct('seed',seed,'quantizedDecoder',quantized);
options.modes={'compact','compact_center','compact_fixed'};
options.channels={struct('name','flat','delays',0,'gains',1), ...
    struct('name','short_multipath','delays',[0 3 9], ...
        'gains',[1 0.25*exp(0.6j) 0.12*exp(-1j)]), ...
    struct('name','late_strong','delays',[0 10 23], ...
        'gains',[0.25 1 0.3*exp(0.7j)]), ...
    struct('name','cp_edge','delays',[0 31],'gains',[0.65 1], ...
        'cfoHz',-220e3,'offset',83), ...
    struct('name','dense','delays',[0 2 5 9 14 18 23 28], ...
        'gains',[0.5 0.2j -0.35 0.25 1 0.3j -0.2 0.25], ...
        'cfoHz',65e3,'offset',11), ...
    struct('name','weak_first','delays',[0 12 25],'gains',[0.12 1 0.3j], ...
        'cfoHz',-65e3,'offset',53)};
for k=1:numel(options.channels)
    options.channels{k}.randomizePhases=randomPhases;
end
rows=run_receiver_comparison(snrDb,nFrames,outPath,options);
end
