function results = run_tracking_comparison(snrDb,nFrames,outPath,seed,stress,quantized)
% Same-capture ablation of phase-aligned MID fusion and temporal pilot PLL.
if nargin<1, snrDb=[3 4]; end
if nargin<2, nFrames=20; end
if nargin<3, outPath=''; end
if nargin<4, seed=202609290; end
if nargin<5, stress=false; end
if nargin<6, quantized=false; end
options=struct('seed',seed,'lengths',1500);
modes={'compact','compact_fused','compact_tracked','compact_tracked_fixed'};
for m=1:numel(modes)
    options.receivers{m}=struct('name',modes{m},'mode',modes{m},'quantized',quantized);
end
options.channels={ ...
    struct('name','awgn','delays',0,'amplitudes',1,'cfoHz',0), ...
    struct('name','short','delays',[0 3 9],'amplitudes',[1 .25 .12],'cfoHz',135e3), ...
    struct('name','cp_edge','delays',[0 31],'amplitudes',[.65 1],'cfoHz',135e3)};
if stress
    options.channels={ ...
        struct('name','late_strong','delays',[0 10 23],'amplitudes',[.25 1 .3],'cfoHz',135e3), ...
        struct('name','dense','delays',[0 2 5 9 14 18 23 28], ...
            'amplitudes',[.5 .2 .35 .25 1 .3 .2 .25],'cfoHz',-220e3), ...
        struct('name','dynamic_200','delays',[0 3 9],'amplitudes',[1 .5 .3], ...
            'cfoHz',135e3,'dopplerHz',[0 200 -200]), ...
        struct('name','dynamic_1000','delays',[0 3 9],'amplitudes',[1 .5 .3], ...
            'cfoHz',135e3,'dopplerHz',[0 1000 -1000])};
end
results=run_sensitivity_sweep(snrDb,nFrames,outPath,options);
end
