#!/usr/bin/env python3
"""Generate synchronous edge-address ROM from the MATLAB QC matrix."""
from pathlib import Path
import re
root=Path(__file__).resolve().parents[1]
source=(root/'+cofdm/ldpc_code.m').read_text().split('B=[')[1].split('];')[0]
base=[[int(v) for v in re.findall(r'-?\d+',row)] for row in source.strip().split(';')]
assert len(base)==12 and all(len(row)==24 for row in base)
words=[]
for row in base:
    edges=[(c,s) for c,s in enumerate(row) if s>=0]
    assert len(edges) in (7,8)
    for i in range(27):
        for j in range(8):
            words.append((((j==len(edges)-1)<<10) | (edges[j][0]*27+(i+edges[j][1])%27)) if j<len(edges) else 0)
p=root/'rtl/cofdm_qcldpc_edge_rom.sv'
lines=['`timescale 1ns/1ps', '// Generated by tools/generate_qcldpc_rom.py from +cofdm/ldpc_code.m.',
'module cofdm_qcldpc_edge_rom(input wire clk, input wire [11:0] addr, output reg [10:0] data);',
'  (* rom_style="block" *) reg [10:0] mem [0:2591];', '  initial begin']
lines += [f"    mem[{i}]=11'h{v:03x};" for i,v in enumerate(words)]
lines += ['  end','  always @(posedge clk) data<=mem[addr];','endmodule','']
p.write_text('\n'.join(lines))
print('Generated 324 check rows, 2376 edges, 2592 ROM entries')
